import { COMMANDS, PREDICATES, createIf, createRepeat } from "./game.js";

const { FORWARD: F, LEFT: L, RIGHT: R } = COMMANDS;

export const LEVELS = [
  {
    name: "First Steps",
    hint: "Three steps to the crystal!",
    width: 5,
    height: 5,
    start: { x: 0, y: 2, direction: "east" },
    rocks: ["1,0", "3,0", "1,4", "4,3"],
    crystals: ["3,2"],
    maxCommands: 3,
    solution: [F, F, F],
  },
  {
    name: "Climb Up",
    hint: "The turtle is looking north.",
    width: 5,
    height: 5,
    start: { x: 1, y: 4, direction: "north" },
    rocks: ["3,0", "3,2", "0,3", "4,4"],
    crystals: ["1,1"],
    maxCommands: 3,
    solution: [F, F, F],
  },
  {
    name: "Power of Repeat",
    hint: "Use one repeat block to move four times!",
    width: 5,
    height: 5,
    start: { x: 0, y: 2, direction: "east" },
    rocks: ["1,0", "3,0", "1,4", "4,3"],
    crystals: ["4,2"],
    maxCommands: 2,
    repeatMoveCount: 4,
    solution: [createRepeat(4, [F])],
  },
  {
    name: "Corner Turn",
    hint: "Walk up, then turn right.",
    width: 5,
    height: 5,
    start: { x: 0, y: 4, direction: "north" },
    rocks: ["0,0", "1,2", "2,3", "4,4"],
    crystals: ["3,1"],
    maxCommands: 7,
    solution: [F, F, F, R, F, F, F],
  },
  {
    name: "Crystal Trail",
    hint: "One program can collect both.",
    width: 5,
    height: 5,
    start: { x: 0, y: 4, direction: "north" },
    rocks: ["1,2", "2,3", "4,0", "4,4"],
    crystals: ["0,1", "3,1"],
    maxCommands: 7,
    solution: [F, F, F, R, F, F, F],
  },
  {
    name: "Staircase",
    hint: "Make a blocky zigzag.",
    width: 5,
    height: 5,
    start: { x: 0, y: 4, direction: "north" },
    rocks: ["0,1", "1,1", "3,1", "3,3", "4,3"],
    crystals: ["2,2", "4,0"],
    maxCommands: 11,
    solution: [F, F, R, F, F, L, F, F, R, F, F],
  },
  {
    name: "Master Miner",
    hint: "Plan one route through all three.",
    width: 6,
    height: 6,
    start: { x: 0, y: 5, direction: "north" },
    rocks: ["1,1", "1,3", "2,4", "4,1", "4,3", "5,5"],
    crystals: ["0,2", "3,2", "3,4"],
    maxCommands: 10,
    solution: [F, F, F, R, F, F, F, R, F, F],
  },
  {
    name: "Pit Stop",
    hint: "Turn away from the pit, then climb to safety.",
    width: 4,
    height: 4,
    start: { x: 1, y: 2, direction: "east" },
    rocks: ["0,0", "3,3"],
    pits: ["2,2"],
    crystals: ["1,0"],
    maxCommands: 3,
    solution: [L, F, F],
  },
  {
    name: "Key Keeper",
    hint: "Collect the key before walking through the door.",
    width: 5,
    height: 3,
    start: { x: 0, y: 1, direction: "east" },
    rocks: ["2,0", "2,2"],
    keys: ["1,1"],
    doors: ["2,1"],
    crystals: ["4,1"],
    maxCommands: 4,
    solution: [F, F, F, F],
  },
  {
    name: "Block Builder",
    hint: "Push the block past the crystal, then step onto it.",
    width: 5,
    height: 3,
    start: { x: 0, y: 1, direction: "east" },
    rocks: ["1,0", "3,2"],
    pushables: ["1,1"],
    crystals: ["3,1"],
    maxCommands: 3,
    solution: [F, F, F],
  },
  {
    name: "Check the Path",
    hint: "Let IF check the blocked path, then turn and check again.",
    width: 3,
    height: 3,
    start: { x: 1, y: 1, direction: "east" },
    rocks: ["2,1"],
    crystals: ["1,0"],
    maxCommands: 5,
    ifPathMove: true,
    solution: [createIf(PREDICATES.PATH_AHEAD, [F]), L, createIf(PREDICATES.PATH_AHEAD, [F])],
  },
  {
    name: "Key Check",
    hint: "Pick up the key, then let IF open the way forward.",
    width: 4,
    height: 3,
    start: { x: 0, y: 1, direction: "east" },
    rocks: ["2,0", "2,2"],
    keys: ["1,1"],
    doors: ["2,1"],
    crystals: ["3,1"],
    maxCommands: 4,
    ifHasKeyMove: true,
    solution: [F, createIf(PREDICATES.HAS_KEY, [F]), F],
  },
];